### ISSUE TITLE
Searching for beers in the search box doesn't seem to work.

### ISSUE THREAD

**Issue by mcpike** [green-brass-doberman/on-tapp#113]
The follow produces no results: 
examples: 
http://ontappapp.com/#!/search/1/sapporo/  
http://ontappapp.com/#!/search/1/coors/
http://ontappapp.com/#!/search/1/blue%20moon/
![screen shot 2015-01-12 at 9 37 40 pm](https://cloud.githubusercontent.com/assets/2506746/5716442/7070698c-9aa3-11e4-9740-2b107b5aa15f.png)
![screen shot 2015-01-12 at 9 38 03 pm](https://cloud.githubusercontent.com/assets/2506746/5716443/70769834-9aa3-11e4-862a-ceee224c1933.png)

**Comment by victorleungtw** [comment]
Thanks Patrick! It's now fixed:)
